### ISSUE TITLE
Allow users to set the size of pxc equals to 1 through percona-xtradb-cluster-operator/deploy/cr.yaml

### ISSUE THREAD

**Issue by kevin-baas** [percona/percona-xtradb-cluster-operator#1733]
### Proposal

When I set pxc to equal 1 through percona-xtradb-cluster-operator/deploy/cr.yaml, it doesn't work

### Is this a feature you are interested in implementing yourself?

No

**Comment by tombojer** [comment]
Deploying the cluster with only one node is working for me.
Because running the cluster with only one node is seen as an unsafe configuration you have to set `allowUnsafeConfigurations` to true.

From the [docs](https://docs.percona.com/percona-operator-for-mysql/pxc/operator.html#perconaxtradbcluster-custom-resource-options):

> `allowUnsafeConfigurations` Prevents users from configuring a cluster with unsafe parameters such as starting the cluster with the number of Percona XtraDB Cluster instances which is less than 3, more than 5, or is an even number, with less than 2 ProxySQL or HAProxy Pods, or without TLS/SSL certificates (if false, unsafe parameters will be automatically changed to safe defaults)
